SELECT *
FROM [PortfolioProject].[dbo].[SalesPortFolio]

--SALES BREAKDOWN


--what is the total profit,revenue,cost and percentage profit of all the product_category.

SELECT Product_Category,sum(revenue) AS Revenue,sum(Profit) as Profit,(sum(Profit)/sum(Revenue))*100 as percentage_profits
FROM [PortfolioProject].[dbo].[SalesPortFolio]
GROUP BY Product_Category
ORDER BY 2 desc



--total sales for each sub_category

SELECT Sub_Category,SUM(revenue) as total_revenue
FROM [PortfolioProject].[dbo].[SalesPortFolio]
GROUP BY Sub_Category
ORDER BY 2 desc



-- percentage  profits of each products
SELECT Product,sum(revenue) AS total_Revenue,sum(Profit) total_profit,sum(cost) as total_cost,(sum(Profit)/sum(Revenue))*100 as percentage_profits
FROM [PortfolioProject].[dbo].[SalesPortFolio]
GROUP BY Product
ORDER BY 5 DESC

--Now to update the table with the percentage_profit


 ALTER TABLE SalesPortFolio --first we alter the table by adding the column and specifing the data type
 ADD Percentage_of_Profit FLOAT

 UPDATE SalesPortFolio  --lastly we update the table by stating the column name and specifing the condition
 SET  Percentage_of_Profit = (Profit/Revenue)*100



-- specific case of the state Yveline in france

SELECT Product,revenue,Cost,Profit,
CASE
	WHEN Profit < 0 THEN 0
	ELSE (Profit/Revenue)*100
END
FROM [PortfolioProject].[dbo].[SalesPortFolio]
WHERE state ='Yveline' 
ORDER BY 4


--what is the age group with the most sales and profit with the total quantity ordered

SELECT Age_Group,SUM(revenue) AS revenue,SUM(profit) as profit,SUM(order_quantity) total_quantity_ordered
FROM [PortfolioProject].[dbo].[SalesPortFolio]
GROUP BY Age_Group
ORDER BY revenue desc



--sales generated by each country

SELECT Country,sum(revenue) as total_revenue
FROM [PortfolioProject].[dbo].[SalesPortFolio]
GROUP BY country
ORDER BY  total_revenue desc


--sales generated by each state

SELECT State,sum(revenue) as total_revenue
FROM [PortfolioProject].[dbo].[SalesPortFolio]
GROUP BY State
ORDER BY  total_revenue desc


--total sales per month

SELECT Month,sum(revenue) as total_revenue
FROM [PortfolioProject].[dbo].[SalesPortFolio]
GROUP BY Month
ORDER BY total_revenue desc


--total sales by year

SELECT year,SUM(revenue) as Sales
FROM [PortfolioProject].[dbo].[SalesPortFolio]
GROUP BY Year
ORDER BY year



--at what month of each year does the most sales happen?

SELECT year,month,sum(revenue) as total_sales
from [PortfolioProject].[dbo].[SalesPortFolio]
group by Year,month
order by 1,3 desc



--Gender per country

SELECT Country,Customer_Gender,count(Customer_Gender) as sum_of_each_gender
FROM [PortfolioProject].[dbo].[SalesPortFolio]
group by country ,Customer_Gender
order by 1,3 desc

--customer age group spreads by country

SELECT Country,State,Age_Group,COUNT(age_group) as count_age_group
FROM [PortfolioProject].[dbo].[SalesPortFolio]
GROUP BY Country,State,Age_Group
ORDER BY 4 desc
